
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'MfpPopup': typeof import("../components/MfpPopup.vue")['default']
    'PageBanner': typeof import("../components/PageBanner.vue")['default']
    'Preloader': typeof import("../components/Preloader.vue")['default']
    'ProgressBar': typeof import("../components/ProgressBar.vue")['default']
    'ScrollTop': typeof import("../components/ScrollTop.vue")['default']
    'ServieceDetailShowcaseRow': typeof import("../components/ServieceDetailShowcaseRow.vue")['default']
    'StaticsticsRow': typeof import("../components/StaticsticsRow.vue")['default']
    'TeamRow': typeof import("../components/TeamRow.vue")['default']
    'VideoShowcase': typeof import("../components/VideoShowcase.vue")['default']
    'CountersCounter': typeof import("../components/counters/Counter.vue")['default']
    'FootersFooter': typeof import("../components/footers/Footer.vue")['default']
    'FootersFooter1': typeof import("../components/footers/Footer1.vue")['default']
    'FootersFooter2': typeof import("../components/footers/Footer2.vue")['default']
    'FootersFooter3': typeof import("../components/footers/Footer3.vue")['default']
    'FootersFooter4': typeof import("../components/footers/Footer4.vue")['default']
    'FootersFooter5': typeof import("../components/footers/Footer5.vue")['default']
    'FootersFooter6': typeof import("../components/footers/Footer6.vue")['default']
    'HeadersHeader': typeof import("../components/headers/Header.vue")['default']
    'HeadersHeader1': typeof import("../components/headers/Header1.vue")['default']
    'HeadersHeader2': typeof import("../components/headers/Header2.vue")['default']
    'HeadersHeader3': typeof import("../components/headers/Header3.vue")['default']
    'HeadersNav': typeof import("../components/headers/Nav.vue")['default']
    'HeadersSearch': typeof import("../components/headers/Search.vue")['default']
    'HeadersSidebar': typeof import("../components/headers/Sidebar.vue")['default']
    'SlidersGallery': typeof import("../components/sliders/Gallery.vue")['default']
    'SlidersHero5': typeof import("../components/sliders/Hero5.vue")['default']
    'SlidersProject': typeof import("../components/sliders/Project.vue")['default']
    'SlidersProject2': typeof import("../components/sliders/Project2.vue")['default']
    'SlidersTestimonial': typeof import("../components/sliders/Testimonial.vue")['default']
    'SlidersTestimonial2': typeof import("../components/sliders/Testimonial2.vue")['default']
    'SlidersTestimonial3': typeof import("../components/sliders/Testimonial3.vue")['default']
    'SlidersTestimonial4': typeof import("../components/sliders/Testimonial4.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtIcon': typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
    'SchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'SchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'SchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'SchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'SchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'SchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'SchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'SchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'SchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'SchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'SchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'SchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'SchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyMfpPopup': typeof import("../components/MfpPopup.vue")['default']
    'LazyPageBanner': typeof import("../components/PageBanner.vue")['default']
    'LazyPreloader': typeof import("../components/Preloader.vue")['default']
    'LazyProgressBar': typeof import("../components/ProgressBar.vue")['default']
    'LazyScrollTop': typeof import("../components/ScrollTop.vue")['default']
    'LazyServieceDetailShowcaseRow': typeof import("../components/ServieceDetailShowcaseRow.vue")['default']
    'LazyStaticsticsRow': typeof import("../components/StaticsticsRow.vue")['default']
    'LazyTeamRow': typeof import("../components/TeamRow.vue")['default']
    'LazyVideoShowcase': typeof import("../components/VideoShowcase.vue")['default']
    'LazyCountersCounter': typeof import("../components/counters/Counter.vue")['default']
    'LazyFootersFooter': typeof import("../components/footers/Footer.vue")['default']
    'LazyFootersFooter1': typeof import("../components/footers/Footer1.vue")['default']
    'LazyFootersFooter2': typeof import("../components/footers/Footer2.vue")['default']
    'LazyFootersFooter3': typeof import("../components/footers/Footer3.vue")['default']
    'LazyFootersFooter4': typeof import("../components/footers/Footer4.vue")['default']
    'LazyFootersFooter5': typeof import("../components/footers/Footer5.vue")['default']
    'LazyFootersFooter6': typeof import("../components/footers/Footer6.vue")['default']
    'LazyHeadersHeader': typeof import("../components/headers/Header.vue")['default']
    'LazyHeadersHeader1': typeof import("../components/headers/Header1.vue")['default']
    'LazyHeadersHeader2': typeof import("../components/headers/Header2.vue")['default']
    'LazyHeadersHeader3': typeof import("../components/headers/Header3.vue")['default']
    'LazyHeadersNav': typeof import("../components/headers/Nav.vue")['default']
    'LazyHeadersSearch': typeof import("../components/headers/Search.vue")['default']
    'LazyHeadersSidebar': typeof import("../components/headers/Sidebar.vue")['default']
    'LazySlidersGallery': typeof import("../components/sliders/Gallery.vue")['default']
    'LazySlidersHero5': typeof import("../components/sliders/Hero5.vue")['default']
    'LazySlidersProject': typeof import("../components/sliders/Project.vue")['default']
    'LazySlidersProject2': typeof import("../components/sliders/Project2.vue")['default']
    'LazySlidersTestimonial': typeof import("../components/sliders/Testimonial.vue")['default']
    'LazySlidersTestimonial2': typeof import("../components/sliders/Testimonial2.vue")['default']
    'LazySlidersTestimonial3': typeof import("../components/sliders/Testimonial3.vue")['default']
    'LazySlidersTestimonial4': typeof import("../components/sliders/Testimonial4.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtIcon': typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
    'LazySchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'LazySchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'LazySchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'LazySchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'LazySchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'LazySchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'LazySchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'LazySchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'LazySchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'LazySchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'LazySchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'LazySchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'LazySchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'LazySchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'LazySchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'LazySchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'LazySchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'LazySchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'LazySchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'LazySchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'LazySchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'LazySchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'LazySchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'LazySchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const MfpPopup: typeof import("../components/MfpPopup.vue")['default']
export const PageBanner: typeof import("../components/PageBanner.vue")['default']
export const Preloader: typeof import("../components/Preloader.vue")['default']
export const ProgressBar: typeof import("../components/ProgressBar.vue")['default']
export const ScrollTop: typeof import("../components/ScrollTop.vue")['default']
export const ServieceDetailShowcaseRow: typeof import("../components/ServieceDetailShowcaseRow.vue")['default']
export const StaticsticsRow: typeof import("../components/StaticsticsRow.vue")['default']
export const TeamRow: typeof import("../components/TeamRow.vue")['default']
export const VideoShowcase: typeof import("../components/VideoShowcase.vue")['default']
export const CountersCounter: typeof import("../components/counters/Counter.vue")['default']
export const FootersFooter: typeof import("../components/footers/Footer.vue")['default']
export const FootersFooter1: typeof import("../components/footers/Footer1.vue")['default']
export const FootersFooter2: typeof import("../components/footers/Footer2.vue")['default']
export const FootersFooter3: typeof import("../components/footers/Footer3.vue")['default']
export const FootersFooter4: typeof import("../components/footers/Footer4.vue")['default']
export const FootersFooter5: typeof import("../components/footers/Footer5.vue")['default']
export const FootersFooter6: typeof import("../components/footers/Footer6.vue")['default']
export const HeadersHeader: typeof import("../components/headers/Header.vue")['default']
export const HeadersHeader1: typeof import("../components/headers/Header1.vue")['default']
export const HeadersHeader2: typeof import("../components/headers/Header2.vue")['default']
export const HeadersHeader3: typeof import("../components/headers/Header3.vue")['default']
export const HeadersNav: typeof import("../components/headers/Nav.vue")['default']
export const HeadersSearch: typeof import("../components/headers/Search.vue")['default']
export const HeadersSidebar: typeof import("../components/headers/Sidebar.vue")['default']
export const SlidersGallery: typeof import("../components/sliders/Gallery.vue")['default']
export const SlidersHero5: typeof import("../components/sliders/Hero5.vue")['default']
export const SlidersProject: typeof import("../components/sliders/Project.vue")['default']
export const SlidersProject2: typeof import("../components/sliders/Project2.vue")['default']
export const SlidersTestimonial: typeof import("../components/sliders/Testimonial.vue")['default']
export const SlidersTestimonial2: typeof import("../components/sliders/Testimonial2.vue")['default']
export const SlidersTestimonial3: typeof import("../components/sliders/Testimonial3.vue")['default']
export const SlidersTestimonial4: typeof import("../components/sliders/Testimonial4.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtIcon: typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyMfpPopup: typeof import("../components/MfpPopup.vue")['default']
export const LazyPageBanner: typeof import("../components/PageBanner.vue")['default']
export const LazyPreloader: typeof import("../components/Preloader.vue")['default']
export const LazyProgressBar: typeof import("../components/ProgressBar.vue")['default']
export const LazyScrollTop: typeof import("../components/ScrollTop.vue")['default']
export const LazyServieceDetailShowcaseRow: typeof import("../components/ServieceDetailShowcaseRow.vue")['default']
export const LazyStaticsticsRow: typeof import("../components/StaticsticsRow.vue")['default']
export const LazyTeamRow: typeof import("../components/TeamRow.vue")['default']
export const LazyVideoShowcase: typeof import("../components/VideoShowcase.vue")['default']
export const LazyCountersCounter: typeof import("../components/counters/Counter.vue")['default']
export const LazyFootersFooter: typeof import("../components/footers/Footer.vue")['default']
export const LazyFootersFooter1: typeof import("../components/footers/Footer1.vue")['default']
export const LazyFootersFooter2: typeof import("../components/footers/Footer2.vue")['default']
export const LazyFootersFooter3: typeof import("../components/footers/Footer3.vue")['default']
export const LazyFootersFooter4: typeof import("../components/footers/Footer4.vue")['default']
export const LazyFootersFooter5: typeof import("../components/footers/Footer5.vue")['default']
export const LazyFootersFooter6: typeof import("../components/footers/Footer6.vue")['default']
export const LazyHeadersHeader: typeof import("../components/headers/Header.vue")['default']
export const LazyHeadersHeader1: typeof import("../components/headers/Header1.vue")['default']
export const LazyHeadersHeader2: typeof import("../components/headers/Header2.vue")['default']
export const LazyHeadersHeader3: typeof import("../components/headers/Header3.vue")['default']
export const LazyHeadersNav: typeof import("../components/headers/Nav.vue")['default']
export const LazyHeadersSearch: typeof import("../components/headers/Search.vue")['default']
export const LazyHeadersSidebar: typeof import("../components/headers/Sidebar.vue")['default']
export const LazySlidersGallery: typeof import("../components/sliders/Gallery.vue")['default']
export const LazySlidersHero5: typeof import("../components/sliders/Hero5.vue")['default']
export const LazySlidersProject: typeof import("../components/sliders/Project.vue")['default']
export const LazySlidersProject2: typeof import("../components/sliders/Project2.vue")['default']
export const LazySlidersTestimonial: typeof import("../components/sliders/Testimonial.vue")['default']
export const LazySlidersTestimonial2: typeof import("../components/sliders/Testimonial2.vue")['default']
export const LazySlidersTestimonial3: typeof import("../components/sliders/Testimonial3.vue")['default']
export const LazySlidersTestimonial4: typeof import("../components/sliders/Testimonial4.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtIcon: typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
export const LazySchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const LazySchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const LazySchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const LazySchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const LazySchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const LazySchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const LazySchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const LazySchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const LazySchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const LazySchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const LazySchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const LazySchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const LazySchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const LazySchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const LazySchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const LazySchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const LazySchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const LazySchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const LazySchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const LazySchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const LazySchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const LazySchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const LazySchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const LazySchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
